const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const PROJECT = "robot-trade-10-strategies-lesson";
const NOTES_DIR = path.join(ROOT, "notes");
const MANIFEST_OUT = path.join(NOTES_DIR, `${PROJECT}-deck.json`);
const REFERENCES_OUT = path.join(NOTES_DIR, `${PROJECT}-references.md`);

const S = {
  edu: "Educational synthesis; not investment advice",
  risk: "CFTC, risk controls and system safeguards for automated trading environments",
  sec: "SEC, Automated Investment Advice and investor alerts",
  testing: "Systematic trading practice: backtest, paper trade, monitor, and risk-control before live use",
};

function slide({
  no,
  role,
  message,
  subtitle,
  support,
  evidence,
  visual = "concept",
  note,
  source = S.edu,
  ...extra
}) {
  return {
    slide_no: no,
    role,
    governing_message: message,
    subtitle,
    supporting_points: support,
    evidence,
    visual_type: visual,
    render_mode: "editable",
    speaker_note: note,
    source,
    ...extra,
  };
}

function strategyBlock({
  start,
  name,
  label,
  thesis,
  when,
  entry,
  exit,
  filters,
  risk,
  metric,
  failure,
}) {
  return [
    slide({
      no: start,
      role: "strategy",
      message: `${label}: ${name}`,
      subtitle: thesis,
      support: [
        `แนวคิดหลัก: ${thesis}`,
        `เหมาะเมื่อ: ${when}`,
        "ให้ robot ทำหน้าที่บังคับวินัย ไม่ใช่ทำนายอนาคตแบบแม่นยำ",
      ],
      evidence: [
        "กลยุทธ์ต้องเขียนเป็น rule ที่ทดสอบซ้ำได้",
        "ห้ามเริ่มจาก optimize parameter จนดูสวยบนอดีต",
      ],
      visual: "metric-summary",
      metrics: [
        { label: "Strategy", value: label.replace("กลยุทธ์ ", "S"), note: name },
        { label: "Core signal", value: metric.signal, note: "ตัวแปรหลัก" },
        { label: "Main risk", value: metric.risk, note: "ต้องคุมก่อน live" },
      ],
      note: `เปิดกลยุทธ์ ${name} ด้วยการย้ำว่า robot trade คือระบบ execute rule ไม่ใช่เครื่องรับประกันกำไร`,
    }),
    slide({
      no: start + 1,
      role: "rules",
      message: `${name} ต้องแปลงเป็นกติกาเข้า-ออกที่ชัดเจน`,
      subtitle: "ถ้าเขียน rule ไม่ได้ robot ก็เทรดแทนเราไม่ได้",
      support: ["ใช้ตารางนี้เป็น template ก่อนเขียน code", "เริ่มจาก rule น้อยข้อและทดสอบง่าย", "แยก entry, exit, filter, sizing ออกจากกัน"],
      evidence: ["Rule ที่ดีต้องตรวจย้อนหลังได้และอธิบายกับคนอื่นได้", "Log ทุก decision เพื่อ debug เมื่อผลจริงไม่ตรง backtest"],
      visual: "table",
      table: [
        ["Component", "Example rule", "Why it matters"],
        ["Entry", entry, "กำหนดจุดเริ่ม trade"],
        ["Exit", exit, "คุมทั้งกำไรและขาดทุน"],
        ["Filter", filters, "ลด trade ในสภาพตลาดผิดแบบ"],
        ["Sizing", risk, "จำกัดความเสียหายต่อไม้"],
      ],
      note: "ใช้ slide นี้ให้ผู้เรียนเห็นว่าแต่ละกลยุทธ์ควรถูกเขียนเป็นระบบ modular ไม่ใช่สูตรเดียวจบ",
    }),
    slide({
      no: start + 2,
      role: "risk",
      message: `${name} แพ้ได้เมื่อสภาพตลาดเปลี่ยนจากสมมติฐาน`,
      subtitle: "Robot ที่ดีต้องรู้ว่าเมื่อไรควรลดขนาดหรือหยุด",
      support: ["กำหนด max loss ต่อวัน/สัปดาห์", "ใส่ kill switch เมื่อ slippage หรือ spread ผิดปกติ", "ตรวจ drawdown และ trade frequency หลังเปิดจริง"],
      evidence: [failure, "CFTC เน้น risk controls, testing, supervision และ safeguards ใน automated trading"],
      visual: "risk",
      risks: [
        { risk: "Overfit", mitigation: "แบ่ง in-sample / out-of-sample และใช้ parameter กว้าง" },
        { risk: "Slippage", mitigation: "ทดสอบด้วย realistic cost และ limit order logic" },
        { risk: "Regime shift", mitigation: "มี market filter และลด size เมื่อ metric เสื่อม" },
        { risk: "Automation failure", mitigation: "ตั้ง order limit, position limit, kill switch และ alert" },
      ],
      note: "ย้ำให้เห็นว่า risk control เป็นส่วนหนึ่งของกลยุทธ์ ไม่ใช่สิ่งที่เติมทีหลัง",
      source: S.risk,
    }),
    slide({
      no: start + 3,
      role: "practice",
      message: `ก่อนใช้ ${name} จริง ให้ผ่าน checklist 5 ข้อ`,
      subtitle: "เป้าหมายคือระบบที่ทนต่อความจริง ไม่ใช่ equity curve ที่สวย",
      support: ["Backtest ด้วยต้นทุนจริง", "Paper trade จน log สะอาด", "กำหนด position limit", "ตั้ง alert และ kill switch", "ทบทวน performance รายสัปดาห์"],
      evidence: ["ถ้าอธิบายเหตุผลของทุก trade ไม่ได้ ยังไม่ควรปล่อย live", "เริ่มเล็กเพื่อเก็บ live data ก่อนเพิ่มขนาด"],
      visual: "roadmap",
      steps: ["Backtest", "Cost", "Paper", "Limit", "Review"],
      note: `ปิดกลยุทธ์ ${name} ด้วย actionable checklist ที่ผู้เรียนเอาไปใช้ต่อได้`,
      source: S.testing,
    }),
  ];
}

const slides = [
  slide({
    no: 1,
    role: "cover",
    message: "10 กลยุทธ์ for Robot Trade",
    subtitle: "สไลด์สอน 50 หน้า: จากแนวคิด กลไก สัญญาณ ความเสี่ยง ไปจนถึง checklist ก่อนเปิดใช้งานจริง",
    support: [
      "Audience: ผู้เริ่มต้นถึงระดับกลางที่อยากสร้างหรือประเมิน trading bot",
      "Focus: rule-based strategy, risk control, backtest discipline",
      "Important: เพื่อการศึกษา ไม่ใช่คำแนะนำการลงทุน",
    ],
    evidence: ["ทุกกลยุทธ์มีช่วงที่แพ้", "ผล backtest ไม่รับประกันผล live"],
    visual: "cover",
    note: "เปิดด้วยกรอบคิดสำคัญ: robot trade ไม่ใช่เครื่องพิมพ์เงิน แต่เป็นเครื่องมือ execute กติกาอย่างมีวินัย",
  }),
  slide({
    no: 2,
    role: "learning-outcomes",
    message: "เรียนจบแล้วต้องแยกให้ออกว่า bot ไหนเป็นระบบ และ bot ไหนเป็นแค่สูตรเสี่ยง",
    subtitle: "เป้าหมายของ deck คือสร้างวิธีคิด ไม่ใช่แจกสูตรลับ",
    support: [
      "เข้าใจ 10 family ของกลยุทธ์ robot trade",
      "รู้ว่าแต่ละกลยุทธ์เหมาะกับสภาพตลาดแบบไหน",
      "ออกแบบ entry, exit, filter, sizing และ kill switch ได้",
      "อ่านผล backtest โดยไม่หลอกตัวเอง",
    ],
    evidence: [
      "กลยุทธ์เดียวไม่ชนะทุกตลาด",
      "ระบบที่ดีต้องวัดทั้ง return, risk, cost, capacity และ operational failure",
    ],
    visual: "roadmap",
    steps: ["Signal", "Rules", "Risk", "Test", "Live"],
    note: "บอกผู้เรียนตั้งแต่ต้นว่า deck นี้เน้น process มากกว่าคำทำนายตลาด",
  }),
  slide({
    no: 3,
    role: "definition",
    message: "Robot trade คือระบบตัดสินใจซ้ำได้ ไม่ใช่ AI ที่รู้อนาคต",
    subtitle: "เริ่มจากคำสั่งที่ชัด แล้วค่อยให้เครื่อง execute",
    support: [
      "Signal: อะไรบอกให้สนใจ trade",
      "Decision: เข้า ออก เพิ่ม ลด หรือไม่ทำอะไร",
      "Execution: ส่ง order อย่างไรให้ต้นทุนไม่บาน",
      "Risk: จำกัดขนาดและหยุดระบบเมื่อผิดปกติ",
    ],
    evidence: [
      "ถ้ากฎเปลี่ยนตามอารมณ์ จะไม่ใช่ systematic trading",
      "ระบบอัตโนมัติขยายทั้งวินัยและความผิดพลาดได้เร็วเท่ากัน",
    ],
    visual: "table",
    table: [
      ["Layer", "Question", "Output"],
      ["Signal", "ตลาดกำลังบอกอะไร", "indicator / feature"],
      ["Rules", "ทำอะไรเมื่อ signal เกิด", "entry / exit"],
      ["Risk", "เสียได้เท่าไร", "size / stop / limit"],
      ["Ops", "ถ้าระบบพังจะหยุดอย่างไร", "alert / kill switch"],
    ],
    note: "ทำให้ผู้เรียนเห็นระบบทั้ง stack ก่อนลงรายละเอียดกลยุทธ์",
  }),
  slide({
    no: 4,
    role: "strategy-map",
    message: "10 กลยุทธ์นี้ครอบคลุมทั้ง trend, reversion, spread, volatility และ risk engine",
    subtitle: "อย่าเลือกกลยุทธ์จากชื่อ ให้เลือกจาก market behavior ที่ต้องการจับ",
    support: [
      "Trend group: ตามแรงต่อเนื่อง",
      "Reversion group: เล่นการเด้งกลับเข้าค่าเฉลี่ย",
      "Relative group: เทียบสินทรัพย์หรือคู่ราคา",
      "Control group: ใช้ filter และ risk engine เพื่อให้ระบบอยู่รอด",
    ],
    evidence: [
      "แต่ละ strategy family มี assumption ต่างกัน",
      "การผสมหลายระบบต้องดู correlation ของผลลัพธ์ ไม่ใช่แค่จำนวน bot",
    ],
    visual: "table",
    table: [
      ["Group", "Strategies", "Best question"],
      ["Trend", "Breakout, MA, Momentum", "แรงไปต่อไหม"],
      ["Reversion", "Mean reversion, Grid", "ยืดเกินไปไหม"],
      ["Relative", "Pairs, Market making", "แพง/ถูกเมื่อเทียบกันไหม"],
      ["Control", "Volatility, Regime, Risk engine", "ควรเทรดแค่ไหน"],
    ],
    note: "ใช้เป็นแผนที่ก่อนเข้า 10 กลยุทธ์",
  }),
  slide({
    no: 5,
    role: "architecture",
    message: "Bot ที่ปล่อยเงินจริงต้องมี 5 ชั้น ไม่ใช่มีแค่ indicator",
    subtitle: "Strategy logic เป็นเพียงชั้นกลางของระบบ",
    support: [
      "Data: ราคา volume spread corporate action",
      "Signal: feature และ rule",
      "Execution: order type, retry, partial fill",
      "Risk: limit, stop, exposure, drawdown",
      "Monitoring: log, alert, report, shutdown",
    ],
    evidence: [
      "ความเสียหายจำนวนมากมาจาก execution และ operational risk",
      "ระบบต้อง test ได้ทั้ง logic และ failure mode",
    ],
    visual: "roadmap",
    steps: ["Data", "Signal", "Order", "Risk", "Monitor"],
    note: "ย้ำว่า deck นี้สอนกลยุทธ์ แต่การใช้งานจริงต้องคิดทั้งระบบ",
    source: S.risk,
  }),
  ...strategyBlock({
    start: 6,
    label: "กลยุทธ์ 1",
    name: "Trend Following Breakout",
    thesis: "ซื้อเมื่อราคาทะลุกรอบสำคัญ และปล่อยให้ trend ทำงาน",
    when: "ตลาดมี momentum ต่อเนื่องและ breakout ตามด้วย volume",
    entry: "Close > high 20 วัน หรือ breakout เหนือ resistance",
    exit: "Trailing stop ด้วย ATR หรือหลุด low ระยะสั้น",
    filters: "เทรดเฉพาะเมื่อ volume สูงกว่าค่าเฉลี่ยและ volatility ไม่แคบเกินไป",
    risk: "เสี่ยง 0.5-1.0% ของทุนต่อ trade และ cap จำนวนสถานะพร้อมกัน",
    metric: { signal: "Breakout", risk: "False break" },
    failure: "แพ้บ่อยในตลาด sideway เพราะเกิด false breakout ต่อเนื่อง",
  }),
  ...strategyBlock({
    start: 10,
    label: "กลยุทธ์ 2",
    name: "Moving Average Crossover",
    thesis: "ใช้เส้นค่าเฉลี่ยเร็ว-ช้าเพื่อจับการเปลี่ยนทิศของ trend",
    when: "ตลาดเริ่มเปลี่ยนจากสะสมพลังไปสู่ directional move",
    entry: "MA 20 ตัดขึ้น MA 50 หรือ price ยืนเหนือ MA หลัก",
    exit: "MA 20 ตัดลง MA 50 หรือ price หลุด MA ที่ใช้เป็น regime",
    filters: "เลี่ยงช่วง ADX ต่ำหรือ range แคบมาก",
    risk: "ลด size เมื่อระยะ stop ไกลเกิน ATR budget",
    metric: { signal: "MA cross", risk: "Whipsaw" },
    failure: "แพ้จาก whipsaw เมื่อราคาแกว่งตัดเส้นไปมาโดยไม่มี trend จริง",
  }),
  ...strategyBlock({
    start: 14,
    label: "กลยุทธ์ 3",
    name: "Mean Reversion",
    thesis: "ซื้อเมื่อราคาลงแรงเกินปกติ และขายเมื่อเด้งกลับสู่ค่าเฉลี่ย",
    when: "ตลาด range-bound และมีแรงกลับค่าเฉลี่ยชัด",
    entry: "RSI ต่ำกว่า 30 หรือ price ต่ำกว่า lower band พร้อมสัญญาณชะลอแรงขาย",
    exit: "กลับถึง moving average, mid-band หรือทำ profit target",
    filters: "ห้ามสวน trend ใหญ่ที่ยังเร่งลง และต้องเช็คข่าว/งบ",
    risk: "ใช้ stop แบบ hard stop เพราะการลงแรงอาจไม่กลับ",
    metric: { signal: "Z-score", risk: "Trend crash" },
    failure: "แพ้หนักเมื่อ mean reversion กลายเป็น catching falling knife",
  }),
  ...strategyBlock({
    start: 18,
    label: "กลยุทธ์ 4",
    name: "Momentum Rotation",
    thesis: "ถือสินทรัพย์ที่แข็งแรงที่สุด และหมุนออกเมื่ออันดับเปลี่ยน",
    when: "มี universe หลายตัว เช่น sector, ETF, crypto basket หรือหุ้นกลุ่มเดียวกัน",
    entry: "เลือก top N จาก return 3-12 เดือนหรือ risk-adjusted momentum",
    exit: "หลุด top rank, momentum ติดลบ หรือ rebalance ตามรอบ",
    filters: "กรอง liquidity, spread และ drawdown ของสินทรัพย์",
    risk: "กระจาย position และตั้ง max weight ต่อ asset/sector",
    metric: { signal: "Rank", risk: "Crowding" },
    failure: "แพ้เมื่อผู้นำกลับตัวพร้อมกัน หรือ momentum crash หลังข่าวใหญ่",
  }),
  ...strategyBlock({
    start: 22,
    label: "กลยุทธ์ 5",
    name: "Grid Trading",
    thesis: "วาง buy/sell เป็นชั้นราคาเพื่อเก็บการแกว่งในกรอบ",
    when: "ตลาดแกว่งใน range และไม่มี trend รุนแรงทางเดียว",
    entry: "ตั้ง grid buy ต่ำกว่าราคาและ sell สูงกว่าราคาเป็นช่วงเท่ากัน",
    exit: "ปิดบางส่วนเมื่อแตะชั้นตรงข้าม หรือหยุดเมื่อหลุดกรอบใหญ่",
    filters: "เปิดเฉพาะเมื่อ volatility เหมาะกับ grid spacing และ spread ไม่กว้าง",
    risk: "จำกัดจำนวนชั้น, max inventory และ stop เมื่อ trend หลุดกรอบ",
    metric: { signal: "Range", risk: "One-way" },
    failure: "แพ้รุนแรงเมื่อราคาไหลทางเดียวแล้วสะสม inventory ผิดฝั่ง",
  }),
  ...strategyBlock({
    start: 26,
    label: "กลยุทธ์ 6",
    name: "Market Making / Spread Capture",
    thesis: "ส่ง bid และ ask เพื่อเก็บ spread พร้อมคุม inventory",
    when: "ตลาด liquid พอ มี spread ให้เก็บ และ latency/fee ไม่เสียเปรียบมาก",
    entry: "วาง quote สองฝั่งรอบ mid-price ตาม spread และ order book imbalance",
    exit: "ยกเลิก quote เมื่อ volatility กระโดดหรือ inventory เกิน limit",
    filters: "งดช่วงข่าว, spread ผิดปกติ, volume บาง หรือ latency สูง",
    risk: "ตั้ง inventory cap, skew quote และ hard kill เมื่อ adverse selection สูง",
    metric: { signal: "Spread", risk: "Inventory" },
    failure: "แพ้จาก adverse selection คือโดน fill เฉพาะฝั่งที่กำลังผิดทาง",
  }),
  ...strategyBlock({
    start: 30,
    label: "กลยุทธ์ 7",
    name: "Pairs Trading / Statistical Arbitrage",
    thesis: "เทรดความสัมพันธ์ของสองสินทรัพย์เมื่อ spread เบี่ยงจากปกติ",
    when: "คู่สินทรัพย์มีเหตุผลพื้นฐานหรือสถิติที่เคลื่อนด้วยกัน",
    entry: "Long ตัวถูก / short ตัวแพง เมื่อ spread z-score เกิน threshold",
    exit: "ปิดเมื่อ z-score กลับใกล้ศูนย์ หรือ relationship break",
    filters: "ตรวจ correlation, cointegration, sector linkage และ borrow cost",
    risk: "จำกัด leverage และหยุดเมื่อ spread widen เกิน stress band",
    metric: { signal: "Z-score", risk: "Breakdown" },
    failure: "แพ้เมื่อความสัมพันธ์เดิมหายไปหรือมี corporate event ทำให้คู่แตก",
  }),
  ...strategyBlock({
    start: 34,
    label: "กลยุทธ์ 8",
    name: "Volatility Breakout / ATR Expansion",
    thesis: "เข้าเทรดเมื่อความผันผวนขยายตัวและราคาเริ่มเลือกทาง",
    when: "ตลาดบีบตัวนาน แล้วเริ่มขยาย range พร้อม direction",
    entry: "ราคา break daily range หรือ ATR expansion พร้อม close ยืนยัน",
    exit: "ATR trailing stop, time stop หรือกลับเข้า range เดิม",
    filters: "เลี่ยง breakout ที่เกิดจาก wick สั้นๆ หรือ volume ต่ำ",
    risk: "ปรับ size ตาม ATR เพื่อให้ risk ต่อ trade คงที่",
    metric: { signal: "ATR", risk: "Spike fade" },
    failure: "แพ้เมื่อ volatility spike แล้วราคากลับเข้ากรอบทันที",
  }),
  ...strategyBlock({
    start: 38,
    label: "กลยุทธ์ 9",
    name: "Regime Filter Strategy",
    thesis: "ไม่ใช่กลยุทธ์เข้า trade โดยตรง แต่เป็นตัวบอกว่า bot ควรเปิดหรือปิด",
    when: "มีหลาย bot และต้องลดการเทรดในตลาดที่ไม่เข้ากับ edge",
    entry: "เปิดระบบเมื่อ trend/volatility/liquidity regime ตรงกับกลยุทธ์",
    exit: "ปิดหรือลด size เมื่อ regime score ต่ำกว่า threshold",
    filters: "ใช้ MA slope, realized volatility, spread, volume และ market breadth",
    risk: "หลีกเลี่ยงการ overfit filter จนตัด trade ดีออกหมด",
    metric: { signal: "Regime", risk: "Late switch" },
    failure: "แพ้โอกาสเมื่อ filter ช้าเกินไป หรือเปลี่ยนสถานะถี่จนเสีย edge",
  }),
  ...strategyBlock({
    start: 42,
    label: "กลยุทธ์ 10",
    name: "Portfolio Risk Engine",
    thesis: "คุมขนาดรวมของหลาย bot ให้พอร์ตอยู่รอดแม้บางกลยุทธ์แพ้",
    when: "มีหลายกลยุทธ์ หลายสินทรัพย์ หรือหลาย timeframe ทำงานพร้อมกัน",
    entry: "อนุญาต trade เฉพาะเมื่อ portfolio exposure ยังไม่เกิน limit",
    exit: "ลดสถานะเมื่อ drawdown, correlation หรือ realized vol เกินเพดาน",
    filters: "เช็ค exposure รวม, sector, direction, leverage และ concentration",
    risk: "กำหนด daily loss limit, max drawdown stop และ capital allocation ต่อ bot",
    metric: { signal: "Exposure", risk: "Correlation" },
    failure: "แพ้เมื่อ bot หลายตัวดูต่างกัน แต่จริงๆ long risk เดียวกันทั้งหมด",
  }),
  slide({
    no: 46,
    role: "testing-workflow",
    message: "Workflow ที่ถูกต้องคือ hypothesis ก่อน backtest ไม่ใช่หา parameter ให้กำไรสูงสุด",
    subtitle: "Backtest ควรตอบว่า edge มีเหตุผลไหม ไม่ใช่ใช้แต่งอดีตให้สวย",
    support: [
      "เขียนสมมติฐานก่อนเห็นผล",
      "แยก in-sample, out-of-sample และ forward test",
      "ใส่ commission, spread, slippage และ partial fill",
      "วัด downside ไม่ใช่ดู CAGR อย่างเดียว",
    ],
    evidence: [
      "ผลที่ดีเกินจริงมักมาจาก look-ahead bias, survivorship bias หรือ cost ต่ำเกินจริง",
      "Paper trading ช่วยตรวจ execution และ logging ก่อนใช้เงินจริง",
    ],
    visual: "roadmap",
    steps: ["Hypothesis", "Backtest", "OOS", "Paper", "Small live"],
    note: "สรุป testing process ที่ผู้เรียนควรใช้กับทุกกลยุทธ์ใน deck",
    source: S.testing,
  }),
  slide({
    no: 47,
    role: "risk-controls",
    message: "Risk controls ต้องอยู่ก่อน order ไม่ใช่หลังขาดทุนแล้วค่อยคิด",
    subtitle: "ระบบควรปฏิเสธ trade ที่เกิน policy ได้เอง",
    support: [
      "Pre-trade: order size, price band, exposure limit",
      "In-trade: stop, trailing stop, time stop, volatility stop",
      "Post-trade: reconciliation, P&L attribution, anomaly review",
      "Emergency: kill switch, cancel all, alert owner",
    ],
    evidence: [
      "CFTC เน้น pre-trade controls, post-trade reports และ system safeguards สำหรับ automated trading",
      "Risk control ที่ดีช่วยลดทั้ง market risk และ operational risk",
    ],
    visual: "table",
    table: [
      ["Control", "Question", "Example"],
      ["Order limit", "ส่ง order ใหญ่เกินไหม", "max notional / max quantity"],
      ["Price band", "ราคา order ผิดปกติไหม", "limit vs last/mid"],
      ["Exposure", "พอร์ตเอียงเกินไหม", "net long / sector cap"],
      ["Kill switch", "ควรหยุดทั้งระบบไหม", "daily loss / error count"],
    ],
    note: "ทำให้ผู้เรียนเห็นว่า risk engine เป็นส่วนหนึ่งของ trading system ไม่ใช่รายงานหลังบ้าน",
    source: S.risk,
  }),
  slide({
    no: 48,
    role: "mistakes",
    message: "ข้อผิดพลาดใหญ่สุดคือเชื่อ backtest มากกว่าระบบควบคุมความเสี่ยง",
    subtitle: "Robot trade พังเร็ว เพราะมันทำผิดซ้ำได้เร็ว",
    support: [
      "ใช้ข้อมูลอนาคตโดยไม่รู้ตัว",
      "ไม่ใส่ต้นทุนจริง",
      "เพิ่ม leverage เพราะ backtest drawdown ต่ำ",
      "ไม่มี log และไม่รู้ว่าทำไม bot เข้า trade",
      "เปิดหลาย bot ที่ถือ risk เดียวกัน",
    ],
    evidence: [
      "ระบบที่ไม่มี kill switch ไม่ควรถูกเรียกว่า production-ready",
      "กลยุทธ์ที่อธิบายไม่ได้หลังแพ้ มักแก้ไม่ได้เมื่อเปิดเงินจริง",
    ],
    visual: "risk",
    risks: [
      { risk: "Backtest illusion", mitigation: "ตรวจ bias และใช้ OOS" },
      { risk: "Cost blindness", mitigation: "ใส่ fee, spread, slippage" },
      { risk: "No ownership", mitigation: "กำหนดคนรับ alert และ shutdown" },
      { risk: "Hidden correlation", mitigation: "วัด exposure รวมทุก bot" },
    ],
    note: "ใช้เป็นบทเรียนรวมก่อนปิด deck",
  }),
  slide({
    no: 49,
    role: "deployment-checklist",
    message: "ก่อน live ให้ถาม 12 ข้อนี้ ถ้าตอบไม่ได้ยังไม่ควรเปิดเงินจริง",
    subtitle: "Checklist นี้สำคัญกว่าสูตร entry",
    support: ["ใช้สำหรับตรวจ strategy, code, broker, risk และ monitoring ก่อน deploy"],
    evidence: ["Live readiness คือการลด unknown unknowns", "เริ่มด้วย capital เล็กและเพิ่มตาม evidence จาก live data"],
    visual: "table",
    table: [
      ["Area", "Checklist"],
      ["Strategy", "สมมติฐานชัด, rule เขียนได้, ไม่ overfit"],
      ["Data", "ไม่มี look-ahead, timezone ถูก, missing data ถูกจัดการ"],
      ["Cost", "fee, spread, slippage, borrow/funding ถูกใส่แล้ว"],
      ["Risk", "size, stop, exposure, daily loss, kill switch พร้อม"],
      ["Execution", "order type, retry, partial fill, cancel logic ผ่าน paper test"],
      ["Monitoring", "log, alert, report, owner และ incident process พร้อม"],
    ],
    note: "สไลด์นี้เป็น output ที่ผู้เรียนควรเอาไปใช้จริง",
    source: S.testing,
  }),
  slide({
    no: 50,
    role: "closing",
    message: "กลยุทธ์ที่ดีไม่ใช่กลยุทธ์ที่ชนะทุกวัน แต่เป็นระบบที่รู้ว่าเสี่ยงอะไรและหยุดเป็น",
    subtitle: "Build small, test honestly, scale only when live evidence supports it",
    support: [
      "เลือก strategy จาก market behavior",
      "เขียน rule ให้ตรวจซ้ำได้",
      "ใส่ risk controls ก่อน live",
      "เก็บ log และเรียนรู้จาก live data",
      "จำไว้ว่า robot trade คือวินัยอัตโนมัติ ไม่ใช่กำไรอัตโนมัติ",
    ],
    evidence: [
      "ทุกระบบมีช่วง drawdown",
      "หน้าที่ของ trader คือคุม risk, process และ behavior ของระบบ",
    ],
    visual: "divider",
    note: "ปิดด้วย mindset ที่ถูกต้อง: robot trade เป็น engineering discipline ผสม market discipline",
  }),
];

const manifest = {
  project_name: PROJECT,
  deck_title: "10 กลยุทธ์ for Robot Trade",
  deck_mark: "ROBOT TRADE LESSON",
  audience: "ผู้เริ่มต้นถึงระดับกลางที่อยากเข้าใจ ออกแบบ หรือประเมิน robot trade / trading bot",
  objective: "สอน 10 กลยุทธ์หลักสำหรับ robot trade พร้อมกติกา ความเสี่ยง วิธีทดสอบ และ checklist ก่อนใช้งานจริง",
  language: "Thai",
  aspect_ratio: "16:9",
  rendering_mode: "editable-first",
  style: "institutional-finance",
  slides,
};

fs.mkdirSync(NOTES_DIR, { recursive: true });
fs.writeFileSync(MANIFEST_OUT, JSON.stringify(manifest, null, 2), "utf8");
fs.writeFileSync(
  REFERENCES_OUT,
  [
    "# Robot Trade 10 Strategies References",
    "",
    "- CFTC: Risk controls and system safeguards for automated trading environments. https://www.cftc.gov/PressRoom/PressReleases/6683-13",
    "- CFTC: Regulation Automated Trading proposal and risk controls. https://www.cftc.gov/PressRoom/PressReleases/7283-15",
    "- SEC: Automated Investment Advice and investor alerts. https://www.sec.gov/about/divisions-offices/office-strategic-hub-innovation-financial-technology-finhub/automated-investment-advice",
    "- Educational synthesis from systematic trading practice: hypothesis, backtest, out-of-sample test, paper trading, risk controls, and monitoring.",
    "",
    "This deck is for education only and is not investment advice.",
  ].join("\n"),
  "utf8"
);

console.log(`[OK] Wrote ${MANIFEST_OUT}`);
console.log(`[OK] Wrote ${REFERENCES_OUT}`);
